export const searchOptions = {
  diets: [
    'balanced',
    'high-protein',
    'high-fiber',
    'low-fat',
    'low-carb',
    'low-sodium',
  ],
  dishes: [
    'Bread',
    'Cereals',
    'Condiments and sauces',
    'Drinks',
    'Desserts',
    'Main course',
    'Pancake',
    'Preps',
    'Preserve',
    'Salad',
    'Sandwiches',
    'Side dish',
    'Soup',
    'Starter',
    'Sweets',
  ],
  cuisines: [
    'American',
    'Asian',
    'British',
    'Caribbean',
    'Central Europe',
    'Chinese',
    'Eastern Europe',
    'French',
    'Indian',
    'Italian',
    'Japanese',
    'Kosher',
    'Mediterranean',
    'Mexican',
    'Middle Eastern',
    'Nordic',
    'South American',
    'South East Asian',
  ],
};
